/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>
#include <string.h>
#include "stm32f4xx.h"
#include "system_stm32f4xx.h"
#include "eeprom.h"
#include "uart.h"
#include "i2c.h"

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

int main(void)
{
	int c;
	char str1[32];
	char str2[32];
	SystemInit();
	UartInit(BAUD_9600);
	EEPROM_Init();
	while(1){
		UartPuts("1. Write Data \r\n");
		UartPuts("1. Read Data \r\n");
		UartGets(str1);
		sscanf(str1,"%d",&c);
		switch(c){
			case 1:UartGets(str2);
				EEPROM_Write(0x0000,(uint8_t*)str2, strlen(str2)+1);
				break;
			case 2:EEPROM_Read(0x0000, (uint8_t*)str2, 32);
				UartPuts(str2);
				break;
		}
	}
	return 0;
}









